apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ratio-app-spot-hpa
  namespace: ratio-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ratio-app-spot
  minReplicas: 8
  maxReplicas: 80
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
